### ISSUE TITLE
Panic PG is not available now

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/watchmarket#144]
```
panic: PG is not available now
goroutine 5 [running]:
github.com/trustwallet/watchmarket/db/postgres.FatalWorker(0x2540be400, 0xc0000adc70)
/build/db/postgres/db.go:52 +0xde
created by main.init.0
/build/cmd/api/main.go:82 +0xc67
```

should not trigger panic if PG is disconnected, since data in the memory

Services to improve:
- [x] prices api
- [x] charts api

**Comment by EnoRage** [comment]
#146
